services:
  - type: web
    name: telegram-data-analyst-bot

    runtime: docker

    dockerfilePath: ./Dockerfile

    autoDeploy: true

    envVars:

      - key: TELEGRAM_BOT_TOKEN
        sync: false

      - key: AIPIPE_TOKEN
        sync: false

      - key: MODEL
        value: gpt-4.1-mini

      - key: GITHUB_TOKEN
        sync: false

      - key: GITHUB_OWNER
        sync: false

      - key: GITHUB_REPO
        sync: false

      - key: GITHUB_BRANCH
        value: main

      - key: LOG_FILE_PATH
        value: run.jsonl
